<?php
/**
 * Copyright © 2010-2018 Epicor Software Corporation: All Rights Reserved
 */
?><?php

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */

?>

<?php
    $helper = $this->helper('Epicor\Comm\Helper\Data');
    $_product = $block->getProduct();
    $isGrouped = $_product->getTypeId() == "grouped" ? true : false;
    $_hasAssociatedProducts = 0;
    if($isGrouped){
        $_associatedProducts = $helper->getAssociatedProducts($_product);
        $_hasAssociatedProducts = count($_associatedProducts) > 0;
    }
?>

<?php
    $showAddToCart = $helper->isFunctionalityDisabledForCustomer('cart') || !$_product->isSaleable() || ($isGrouped && !$_hasAssociatedProducts)? false : true;
    $erpAccount = $helper->getErpAccountInfo();
        /* @var $erpAccount Epicor_Comm_Model_Customer_Erpaccount */
    if($erpAccount) {
        if ($erpAccount->getAccountType() == Epicor\Comm\Model\Customer\Erpaccount::CUSTOMER_TYPE_B2B) {
            $licenseTypes = array('Customer_Configurator');
        } else {
            $licenseTypes = array('Consumer_Configurator');
        }
    } else {
        $licenseTypes = array();
    }
    
    $this->setLicensed($this->helper('Epicor\Common\Helper\Data')->isLicensedFor($licenseTypes));
    $locHelper = $this->helper('Epicor\Comm\Helper\Locations');
    /* @var $helper Epicor_Comm_Helper_Locations */

    $showLocations = $locHelper->isLocationsEnabled();
    $customerLocations = $_product->getCustomerLocations();
    $singleLocation = count($_product->getCustomerLocations()) == 1;
    
    if ($singleLocation) {
        $location = array_pop($customerLocations);
        $_product->setToLocationPrices($location);
    }
    
$returnUrl = $this->getRequest()->getParam('returnurl');
$stockVisibility = $this->helper('Epicor\Common\Helper\Data')->getScopeConfig()->getValue('epicor_comm_locations/global/stockvisibility');
    $allSourceLocations = ($this->helper('Epicor\Common\Helper\Data')->getScopeConfig()->getValue('epicor_comm_locations/global/stockvisibility', \Magento\Store\Model\ScopeInterface::SCOPE_STORE) == 'all_source_locations') ? true : false;
$groupOrConfigurable = in_array($_product->getTypeId(),array('grouped','configurable')) ? true : false;
?>

<?php $reconfigureCart = $this->getRequest()->getParam('recon'); ?>
<?php $buttonTitle = ($reconfigureCart) ? 'Update Cart' : 'Add to Cart'  ; ?>
<?php $itemId = $this->getRequest()->getParam('itemid');?>
<div class="box-tocart">
    <div class="fieldset">
                                                   
            <?php if ($showLocations && count($customerLocations) && !$singleLocation && !$allSourceLocations && !$groupOrConfigurable):  ?>
                <?php echo $block->setProduct($_product)->getChildChildHtml('epicor_commlocations_container', false) ?>
                <?php echo $block->setProduct($_product)->getChildChildHtml('epicor_commlocations_container.additional', false) ?>
           <?php endif; ?> 
            <?php if ($_product->getEccConfigurator()): ?> 
            <?php if ($this->getLicensed()): ?> 
                <?php echo $block->getChildChildHtml('configurableaddtocart_container') ?> 
                <?php echo $block->getChildChildHtml('configurableaddtocart_container.additional') ?> 
            <?php endif; ?>                           
        <?php else : ?>
        <?php if ($block->shouldRenderQuantity()): ?>
        
         <?php if ((
            !$showLocations || $allSourceLocations || ( $singleLocation) || (in_array($stockVisibility, array('default', 'logged_in_shopper_source', 'all_source_locations'))
            )
        )): ?>
        
        
        <?php if($showAddToCart):?>
            <?php if($reconfigureCart):?>
                <input type="hidden" name="cart_item_id" value="<?php echo $itemId ?>" title="Update Config Value" />
                <input type="hidden" name="update_config_value" value="true" title="Update Config Value" />        
            <?php endif;?>    

            <div class="field qty">
                <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                
                <div class="control">
                    <div class="qty-minus"> <a class="btn-qty minus" href="#">-</a></div>
                    <div class="qty-input">
                        <input type="number"
                           name="qty"
                           id="qty"
                           maxlength="12"
                           value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                           title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                           data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                           />
                    </div>
                    <div class="qty-plus"> <a class="btn-qty plus" href="#">+</a></div>
                </div>
            </div>
            <script type="text/javascript">
                require(['jquery','domReady!'],function($){
                    $(".btn-qty").click(function (event) {
                        var $button = $(this);
                        var oldValue = $button.closest('.control').find("input#qty").val();
                        var defaultValue = <?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>;
                        if ($button.hasClass('plus')) {
                            var newVal = parseFloat(oldValue) + 1;
                        } else {
                            if (oldValue > defaultValue) {
                                var newVal = parseFloat(oldValue) - 1;
                            } else {
                                newVal = defaultValue;
                            }
                        }
                        $button.closest('.control').find("input#qty").val(newVal);
                        event.preventDefault();
                    });

                });
                </script>

        <?php endif; ?>
        
        <?php endif; ?>
            
            
        <?php endif; ?>
        
         <?php if ($showLocations) : ?>
        
            <?php if ($singleLocation): ?>
                <?php $locationCode = key($_product->getCustomerLocations());?>
                <input type="hidden" name="location_code" value="<?php echo $locationCode; ?>"/>
            <?php endif; ?>
            <?php if ($returnUrl): ?>
                <input type="hidden" name="return_url" value="<?php echo base64_decode($returnUrl); ?>" />
            <?php endif; ?>
                
        <?php endif; ?>
        <?php if($showAddToCart):?> 
            <?php if($reconfigureCart):?>
                <input type="hidden" name="cart_item_id" value="<?php echo $itemId ?>" title="Update Config Value" />
                <input type="hidden" name="update_config_value" value="true" title="Update Config Value" />        
            <?php endif;?>                
            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
            </div>
        <?php endif; ?>
        <?php endif; ?>
        <?php echo $block->getChildHtml('', true) ?>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
