<?php
/**
 * Copyright © 2010-2018 Epicor Software Corporation: All Rights Reserved
 */
?><?php

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helperMsrp = $this->helper('Magento\Msrp\Helper\Data');
$helper = $this->helper('Epicor\Comm\Helper\Data');

$canApplyMsrp = $helperMsrp->isShowBeforeOrderConfirm($product) && $helperMsrp->isMinimalPriceLessMsrp($product);

$commonHelper = $this->helper('Epicor\Common\Helper\Data');

$unit_price_precision = $commonHelper->getScopeConfig()->getValue('checkout/options/unit_price_precision', \Magento\Store\Model\ScopeInterface::SCOPE_STORE) ? : 2;
$unit_price_tax_precision = $commonHelper->getScopeConfig()->getValue('checkout/options/unit_price_tax_precision', \Magento\Store\Model\ScopeInterface::SCOPE_STORE) ? : 2;
$row_total_precision = $commonHelper->getScopeConfig()->getValue('checkout/options/row_total_precision', \Magento\Store\Model\ScopeInterface::SCOPE_STORE) ? : 2;
$row_total_tax_precision = $commonHelper->getScopeConfig()->getValue('checkout/options/row_total_tax_precision', \Magento\Store\Model\ScopeInterface::SCOPE_STORE) ? : 2;

$showUom = $commonHelper->getScopeConfig()->isSetFlag(
            'Epicor_Comm/units_of_measure/display_in_cart',
            \Magento\Store\Model\ScopeInterface::SCOPE_STORE
        );
$showInColumn = $commonHelper->getScopeConfig()->isSetFlag(
            'Epicor_Comm/units_of_measure/display_in_cart_column',
            \Magento\Store\Model\ScopeInterface::SCOPE_STORE
        );

$ewaHelper = $this->helper('Epicor\Comm\Helper\Configurator');
/* @var $helper \Epicor\Comm\Helper\Configurator */

$taxHelper = $this->helper('Magento\Tax\Helper\Data');
/* @var $taxHelper \Magento\Tax\Helper\Data */

$contractHelper = $this->helper('Epicor\Lists\Helper\Frontend\Contract');
/* @var $contractHelper \Epicor\Lists\Helper\Frontend\Contract */


$displayContractDrop = $_item->getQuote()->canDisplayCartContracts();

$locHelper = $this->helper('Epicor\Comm\Helper\Locations');
        /* @var $locHelper Epicor_Comm_Helper_Locations */

$showLoc = $locHelper->isLocationsEnabled();
$showLocInColumn = false;
        
$showLoc = ($showLoc) ? $locHelper->showIn('cart') : false;
$showLocInColumn = ($showLoc) ? $locHelper->showColumnIn('cart') : false;
  
/* Below  code not needed becuase  moved into file
 *Epicor\Comm\view\frontend\templates\cart\item\renderer\actions\edit.phtml;
  */
/*
$groupParentId = method_exists($block, 'isGroupProduct') ? $block->isGroupProduct($_item->getProduct()) : false;
if($groupParentId){
    $groupedProductUrlPath = $block->getProductUrlPath($groupParentId);
}
*/

$parentId = $this->getProduct()->getParentIdsByChild($this->getProduct()->getId());
//M1 > M2 Translation End
$productIsGroupedAndParentVisible = false;
if(isset($parentId[0]) && $parentId[0]){   // if true, product is grouped
    //M1 > M2 Translation Begin (Rule p2-1)
	//$parent = Mage::getModel('catalog/product')->load($parentId[0]);
	$parent = $block->getProduct()->load($parentId[0]);
    //M1 > M2 Translation End
	$productIsGroupedAndParentVisible = ($parent->getVisibility() != 1) ? true : false;
	$block->setProductUrl($parent->getProductUrl());
	$productUrl = $parent->getProductUrl();
}else{
	$productUrl = $block->getProductUrl(); 
}
?>
<tbody class="cart-table cart item">
    <tr class="item-info">
        <td data-th="<?php echo $block->escapeHtml(__('Item')); ?>" class="col item">
            <?php if ($block->hasProductUrl()):?>
                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"
                   title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else:?>
                <span class="product-item-photo">
            <?php endif;?>
            <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
            <?php if ($block->hasProductUrl()):?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl() || $productIsGroupedAndParentVisible):?>
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?php echo $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <div class="product-cart-sku">
                    <span class="label"><?php echo __('SKU'); ?>:</span> <?php echo $this->escapeHtml($_item->getOptionByType('ewa_sku') ?: $helper->removeUOMSeparator($_item->getSku())); ?>
                </div>
                    <?php if ($_options = $this->getOptionList()): ?>
                    <dl class="item-options">
                            <?php foreach ($_options as $_option) : ?>
                                <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                                <?php if (!isset($_option['option_type']) || substr($_option['option_type'], 0, 4) != 'ewa_' || $ewaHelper->getEwaDisplay($_option['option_type'])) : ?>
                                    <?php if (!isset($_option['option_type']) || substr($_option['option_type'], 0, 4) != 'ewa_'): ?>
                                        <dt><?php echo $this->escapeHtml(__($_option['label'])) ?></dt>
                                    <?php endif; ?>  
                                    <?php if (isset($_option['option_type'])){
                                        $optionText = "_".$_option['option_type'];
                                    }else{
                                        $optionText = "";
                                    } ?>
                                    <dd id="cart_item_options_<?php echo $optionText; ?>" <?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
                                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                            <div class="truncated_full_value">
                                                <dl class="item-options">
                                                    <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                                                    <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                                                </dl>
                                            </div>
                                        <?php endif; ?>
                                    </dd>                          
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </dl>
                    <?php endif; ?>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="cart item message <?php /* @escapeNotVerified */ echo $message['type'] ?>"><div><?php echo $block->escapeHtml($message['text']) ?></div></div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>
    <?php if ($showUom && $showInColumn) : ?>
          <td class="col msrp" data-th="<?php echo $block->escapeHtml(__('UOM')); ?>">
            <?php
                echo __($_item->getProduct()->getEccPackSize());
            ?>
        </td> 
    <?php endif; ?>
        
    <?php if($showLoc && $showLocInColumn) :?>
        <td class="col location" data-th='<?php echo $block->escapeHtml(__('Location')); ?>'> 
            <?php
            echo __($_item->getEccLocationName());
            ?>
        </td>
    <?php endif; ?>

    <?php if ($displayContractDrop) : ?>
        <td>
           <?php
           echo $contractHelper->cartItemContractDisplay($_item);
           ?>
        </td>
    <?php endif; ?>

        <?php if ($canApplyMsrp): ?>
            <td class="col msrp" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId;?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
                        <span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
                    </a>
                </span>
            </td>
        <?php else: ?>
            <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
            <?php 
                $unitBlock = $this->getLayout()->getBlock('checkout.item.price.unit');
                $unitBlock->setItem($_item);
            ?>
                
            <?php if ($taxHelper->displayCartPriceInclTax() || $taxHelper->displayCartBothPrices()): ?>
                <span class="price-including-tax" data-label="<?php echo $block->escapeHtml(__('Incl. Tax')); ?>">
                    <?php if ($unitBlock->displayPriceWithWeeeDetails()): ?>
                        <span class="cart-tax-total"
                            data-mage-init='{"taxToggle": {"itemTaxId" : "#unit-item-tax-details<?php /* @escapeNotVerified */ echo $_item->getId(); ?>"}}'>
                    <?php else: ?>
                        <span class="cart-price">
                    <?php endif; ?>
                        <?php /* @escapeNotVerified */ echo $unitBlock->formatPrice($unitBlock->getUnitDisplayPriceInclTax()); ?>
                        </span>

                    <?php if ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item)): ?>
                        <span class="cart-tax-info" id="unit-item-tax-details<?php /* @escapeNotVerified */ echo $_item->getId(); ?>" style="display: none;">
                            <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                                <span class="weee" data-label="<?php /* @escapeNotVerified */ echo $tax['title']; ?>">
                                    <?php /* @escapeNotVerified */ echo $unitBlock->formatPrice($tax['amount_incl_tax'], true, true); ?>
                                </span>
                            <?php endforeach; ?>
                        </span>

                        <?php if ($unitBlock->displayFinalPrice()): ?>
                            <span class="cart-tax-total"
                                data-mage-init='{"taxToggle": {"itemTaxId" : "#unit-item-tax-details<?php /* @escapeNotVerified */ echo $_item->getId(); ?>"}}'>
                                <span class="weee" data-label="<?php echo $unitBlock->escapeHtml(__('Total Incl. Tax')); ?>">
                                    <?php /* @escapeNotVerified */ echo $unitBlock->formatPrice($unitBlock->getFinalUnitDisplayPriceInclTax()); ?>
                                </span>
                            </span>
                        <?php endif; ?>
                    <?php endif; ?>
                </span>
            <?php endif; ?>
                    
            <?php if ($taxHelper->displayCartPriceExclTax() || $taxHelper->displayCartBothPrices()): ?>
                <?php //echo $block->getUnitPriceHtml($_item); ?>
                <?php if ($this->helper('Magento\Weee\Helper\Data')->typeOfDisplay(array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php $price = $_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition(); ?>
                <?php else: ?>
                    <?php $price = $_item->getCalculationPrice(); ?>
                <?php endif; ?>
                <?php if($_item->getQuote()->isSalesRep()): // IF SALES REP
                        $pricingRuleProductHelper = $this->helper('Epicor\SalesRep\Helper\Pricing\Rule\Product');
                        /* @var $pricingRuleProductHelper Epicor_SalesRep_Helper_Pricing_Rule_Product */
                        $_product = $_item->getProduct();
                        $_product->setEwaSku($_item->getOptionByType('ewa_sku'));
                        $_product->setEccMsqBasePrice($_item->getEccMsqBasePrice());
                        $basePrice = !is_null($_item->getEccOriginalPrice()) ? $_item->getEccOriginalPrice() : $price;
                        $minPrice = $pricingRuleProductHelper->getMinPrice($_product, $basePrice);
                        $rulePrice = !is_null($_item->getEccSalesrepRulePrice()) ? $_item->getEccSalesrepRulePrice() : $basePrice;
                        $maxDiscount = $pricingRuleProductHelper->getMaxDiscount($_product, $basePrice);
                        $salesRepPrice = !is_null($_item->getEccSalesrepPrice()) ? $_item->getEccSalesrepPrice() : $price;
                        if ($basePrice > 0 && $rulePrice > 0 && $rulePrice > $minPrice): ?>
                        <div class="salesrep-discount-container salesrep-cart" id="cart-item-<?php echo $_item->getId() ?>">
                        <span class="left discount-currency"><?php echo str_replace(array('1','0','.',','), array(''),  $this->getProduct()->getStore()->getCurrentCurrency()->formatPrecision(1, 0, array(), false)); ?></span>
                        <input type="text" salesrep-cartid="<?php echo $_item->getId(); ?>" 
                               salesrep-type="price" 
                               name="cart[<?php echo $_item->getId() ?>][calculation_price]" 
                               min-value="<?php echo $minPrice; ?>" 
                               base-value="<?php echo $rulePrice; ?>" 
                               orig-value="<?php echo $salesRepPrice; ?>" 
                               web-price-value="<?php echo $basePrice; ?>" 
                               value="<?php echo $salesRepPrice; ?>" 
                               size="12" title="<?php echo __('Price') ?>" 
                               class="input-text price" maxlength="20" /><br />
                    <span class="left"><?php echo __('Discount'); ?></span>
                    <input type="text" salesrep-cartid="<?php echo $_item->getId(); ?>" 
                           salesrep-type="discount" 
                           name="cart[<?php echo $_item->getId() ?>][discount_percent]" 
                           max-value="<?php echo $maxDiscount ?>" 
                           orig-value="<?php echo $_item->getEccSalesrepDiscount() ?: '0' ?>" 
                           value="<?php echo $_item->getEccSalesrepDiscount() ?: '0' ?>" 
                           size="4" title="<?php echo __('Discount') ?>" 
                           class="input-text discount" maxlength="12" /><span class="discount-percentage">%</span><br />
                    <?php $resetStyle = ($basePrice == $salesRepPrice) ? 'style="display:none"' : ''; ?>
                    <div class="reset-discount" id="reset_discount_<?php echo $_item->getId(); ?>" item-id="<?php echo $_item->getId(); ?>"<?php echo $resetStyle; ?>>
                        <a href="javascript:window.salesrepPricing.resetDiscount('<?php echo $_item->getId(); ?>')"><?php echo __('Revert to Web Price') ?></a></div>
                    </div>
                    </div>
                    <input type="hidden" name="salesrep_loading_image" id="salesrep_loading_image" value="<?php echo $this->getViewFileUrl('Epicor_Customerconnect::epicor/customerconnect/images/ajax-loader-tr.gif') ?>" />
                    <?php else: ?>
                        <?php echo  $this->getProduct()->getStore()->getCurrentCurrency()->formatPrecision($price, $unit_price_precision); ?>
                    <?php endif; ?>
                <?php else: ?>
                    <span class="price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Excl. Tax')); ?>">
                        <?php if ($unitBlock->displayPriceWithWeeeDetails()): ?>
                                <span class="cart-tax-total"
                                    data-mage-init='{"taxToggle": {"itemTaxId" : "#eunit-item-tax-details<?php /* @escapeNotVerified */ echo $_item->getId(); ?>"}}'>
                        <?php else: ?>
                            <span class="cart-price">
                        <?php endif; ?>
                                <?php /* @escapeNotVerified */ echo $unitBlock->formatPrice($price); ?>
                            </span>
                    </span>
                <?php endif; // ENDIF SALES REP?>                                
            <?php endif; ?>
            </td>
        <?php endif; ?>
        <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
            <div class="field qty">
                <label class="label" for="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty">
                    <span><?php /* @escapeNotVerified */ echo __('Qty') ?></span>
                </label>
                <div class="control qty">
                    <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                           name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                           data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                           value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
                           type="number"
                           size="4"
                           title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                           class="input-text qty"
                           maxlength="12"
                           data-validate="{required:true,'validate-greater-than-zero':true, 'validatedecimalplace':<?php echo $helper->getDecimalPlaces($_item->getProduct()); ?>}"
                           data-role="cart-item-qty"/> 
                       <button type="submit" style="display:none" name="update_cart_action" value="update_qty" title="<?php echo __('Update'); ?>" class="button btn-update"><span><span><?php echo __('Update'); ?></span></span>
        </button>
                    <?php if ($showUom && !$showInColumn) : ?>
                    <span>
                        <?php 
                        echo ' x ' . __($_item->getProduct()->getEccPackSize());
                        ?>
                    </span>
                    <?php endif; ?>
                </div>
            </div>
        </td>

        <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal'));?>">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else: ?>
                <?php echo $block->getRowTotalHtml($_item); ?>
            <?php endif; ?>
        </td>
    </tr>
    <tr class="item-actions">
        <td colspan="100">
            <div class="actions-toolbar">
                <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>

<script type="text/javascript">
    require([
            "jquery"
    ],function($){
        
        $('.input-text.qty').focus(function(){
          var val = $(this).val();
          $(this).next('button').show();
        });
            
    })
</script>