<?php
/**
 * Copyright © 2010-2018 Epicor Software Corporation: All Rights Reserved
 */
?><?php

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
?>
<div class="lead-time">
    <?php if ($_product->getData('ecc_lead_time')): ?>
        <?php echo $_product->getData('ecc_lead_time'); ?>
    <?php endif; ?>
</div>
