<?php
/**
 * Copyright © 2010-2018 Epicor Software Corporation: All Rights Reserved
 */
?><?php

// @codingStandardsIgnoreFile

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
$helper = $this->helper('Epicor\Comm\Helper\Data');
/* @var $helper Epicor\Comm\Helper\Data */


$ewaHelper = $this->helper('Epicor\Comm\Helper\Configurator');

// Start B2B hide prices
$eccHidePrices = $helper->getEccHidePrice();
$showPrices = true;
if ($eccHidePrices || $helper->isFunctionalityDisabledForCustomer('prices')){
    $showPrices = false;
}
// End B2B hide prices

$contractHelper = $this->helper('Epicor\Lists\Helper\Frontend\Contract');
/* @var $contractHelper Epicor\Lists\Helper\Frontend\Contract */

$listEnabled = $contractHelper->contractsEnabled();
?>
<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
    <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <strong class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()): ?>
        <dl class="item-options">
        <?php foreach ($_options as $_option) : ?>
            <?php  if (!isset($_option['option_type']) || ($ewaHelper->getEwaDisplay($_option['option_type']))) : ?>
            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
            <?php if (!$block->getPrintStatus()): ?>
                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                <dd>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                        <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                    <?php else: ?>
                        <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                    <?php endif; ?>
                </dd>
            <?php else: ?>
                <dd>
                    <?php echo nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
                </dd>
            <?php endif; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) :?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>">
        <?php /* @escapeNotVerified */ //echo $block->prepareSku($block->getSku()) ?>
        <?php echo $this->escapeHtml($this->helper('Epicor\Common\Helper\Data')->getSku($block->getSku())) ?>
    </td>
    <td class="col uom" data-th="<?php echo $block->escapeHtml(__('UOM')); ?>">
        <?php echo $this->escapeHtml($this->helper('Epicor\Common\Helper\Data')->getUom($this->getSku())) ?>
    </td>
    <?php if($block->getShowLocations() && $block->getShowLocationsColumn()): ?>
        <td class="col uom" data-th="<?php echo $block->escapeHtml(__('Location')); ?>">
            <?php echo $block->getItemLocationName(); ?>
        </td>
    <?php endif; ?>
    <?php if ($listEnabled) : ?>
        <td class="col uom" data-th="<?php echo $block->escapeHtml(__('Contract')); ?>">
            <?php echo $block->escapeHtml($_item->getEccContractCode()); ?>
        </td>
    <?php endif; ?>
    <?php if($showPrices) : ?>
        <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
            <?php echo $block->getItemPriceHtml(); ?>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
        <ul class="items-qty">
        <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
            <li class="item">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Ordered'); ?></span>
                <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyOrdered()*1 ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyShipped() > 0): ?>
            <li class="item">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Shipped'); ?></span>
                <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyShipped()*1 ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
            <li class="item">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Canceled'); ?></span>
                <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyCanceled()*1 ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
            <li class="item">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Refunded'); ?></span>
                <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyRefunded()*1 ?></span>
            </li>
        <?php endif; ?>
        </ul>
    </td>
    <?php if($showPrices) : ?>
        <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
            <?php echo $block->getItemRowTotalHtml(); ?>
        </td>
    <?php endif; ?>
    <td style="padding: 0;min-width: 0;width: 0;"></td>
    <td style="padding: 0;min-width: 0;width: 0;"></td>
    <td style="padding: 0;min-width: 0;width: 0;"></td>
    <td style="padding: 0;min-width: 0;width: 0;"></td>
</tr>
