<?php

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
/**
 * Product list Ajax template
 *
 * @var $block \Epicor\Comm\Block\Catalog\Product\ListProduct
 */
?>

<?php $_product = $this->getProduct();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$block->setProductPrices($_product);
//$block->setListMode($this->getMode());

if ($block->getMode() == 'grid') {
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
} else {
    $viewMode = 'list';
    $image = 'category_page_list';
    $showDescription = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
}
/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();

$_productNameStripped = $block->stripTags($_product->getName(), null, true);
//hide price check
$commHelper = $this->helper('Epicor\Comm\Helper\Data');
$eccHideCheckout = $commHelper->getEccHidePrice();
$eccHideCheckout = $eccHideCheckout && $eccHideCheckout != 3 ? true : false;
?>

<?php if ($block->showPriceOnConfiguration($_product)): ?>
    <div class="price-box"><span class="price"><?php echo __('Price on configuration'); ?></span></div>
<?php elseif ($_product->isSalable()) : ?>
    <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
<?php endif; ?>

<?php //echo $this->getChildHtml('epicor_ecc_stock_display_ajax', false); ?>

<?php echo $block->getProductDetailsHtml($_product); ?>
<div class="cdz-product-bottom hover-effect">
    <div class="cdz-buttons-container">
        <div class="cdz-buttons-inner">

            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                <?php // EPICOR ECC START >>> ?>
                <?php $showAddToCart = false; ?>
                <?php if ($block->showAddToCart($_product) && !$eccHideCheckout) : ?>
                    <?php $showAddToCart = true; ?>
                    <?php // EPICOR ECC END <<< ?>
                    <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                        <?php if ($_product->isSaleable() && !$_product->canConfigure()): ?>
                            <?php // EPICOR ECC START >>> ?>
                            <?php if ($block->showLocations()): ?>
                                <?php echo $this->getChildHtml('epicor_ecc_product_list_locations_ajax', false) ?>
                            <?php elseif ($_product->getEccConfigurator()): ?>
                                <?php echo $this->getChildHtml('epicor_ecc_product_configurator_ajax', false) ?>
                            <?php elseif ($_product->getTypeId() == 'grouped' || $_product->getTypeId() == 'configurable'): ?>
                                <form action="<?php /* @escapeNotVerified */ echo $_product->getProductUrl(); ?>">
                                    <button type="submit"
                                            title="<?php echo $block->escapeHtml(__('View Details')); ?>"
                                            class="action tocart primary">
                                        <span><?php /* @escapeNotVerified */ echo __('View Details') ?></span>
                                    </button>
                                </form>
                            <?php else: ?>
                                <?php // EPICOR ECC END <<< ?>
                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    <button type="submit"
                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                            class="action tocart primary">
                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                    </button>
                                    <?php echo $this->getChildHtml('epicor_ecc_product_list_related_branch_ajax', false) ?>
                                    <?php // EPICOR ECC START >>> ?>
                                    <?php if ($_product->getTypeId() == 'bundle'): ?>
                                        <?php $selectionCollection = $_product->getTypeInstance(true)->getSelectionsCollection($_product->getTypeInstance(true)->getOptionsIds($_product), $_product); ?>
                                        <?php foreach ($selectionCollection as $option) : ?>
                                            <input type="hidden" name="bundle_option[<?php echo $option['option_id']; ?>]" value="<?php echo $option['selection_id']; ?>" />
                                        <?php endforeach; ?>
                                    <?php endif; ?>

                                    <?php if ($block->getSingleLocation()): ?>
                                        <input type="hidden" name="location_code" value="<?php echo $block->getSingleLocation()->getLocationCode(); ?>" />
                                    <?php endif; ?>

                                </form>
                                <?php // EPICOR ECC START >>> ?>
                            <?php endif; ?>
                        <?php elseif($_product->isSaleable() && $_product->canConfigure()): ?>
                            <form action="<?php /* @escapeNotVerified */ echo $_product->getProductUrl(); ?>">
                                <button type="submit"
                                        title="<?php echo $block->escapeHtml(__('View Details')); ?>"
                                        class="action tocart primary">
                                    <span><?php /* @escapeNotVerified */ echo __('View Details') ?></span>
                                </button>
                            </form>
                        <?php else: ?>
                            <div class="stock unavailable"><span><?php echo __('Product currently unavailable'); ?></span></div>
                        <?php endif; ?>
                        <?php // EPICOR ECC END <<< ?>
                    </div>
                <?php endif; ?>
                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                    <?php if(!$showAddToCart|| $eccHideCheckout): ?>
                        <?php if ($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                            <form action="<?php /* @escapeNotVerified */ echo $_product->getProductUrl(); ?>">
                                <button type="submit" title="<?php echo $block->escapeHtml(__('View Details')); ?>" class="action tocart primary">
                                    <span><?php /* @escapeNotVerified */ echo __('View Details') ?></span>
                                </button>
                            </form>
                        <?php else: ?>
                            <div class="stock unavailable"><span><?php echo __('Product currently unavailable'); ?></span></div>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                        <?php //echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                        <?php
                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                        ?>
                        <a href="#"
                               class="action tocompare show-tooltip"
                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                               role="button">
                                <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                            </a>
                        <a href="#"
                                   class="action towishlist"
                                   title="<?php echo $block->escapeHtml(__('Saved Products')); ?>"
                                   aria-label="<?php echo $block->escapeHtml(__('Saved Products')); ?>"
                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                   data-action="add-to-wishlist"
                                   role="button">
                                    <span><?php /* @escapeNotVerified */ echo __('Saved Products') ?></span>
                                </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
<div>
