<?php
/**
 * Copyright © 2010-2018 Epicor Software Corporation: All Rights Reserved
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
use Magento\Framework\App\Action\Action;
$_LoaderHelper = $this->helper('Epicor\Comm\Helper\LazyLoader');
$commHelper = $this->helper('Epicor\Comm\Helper\Data');
/* @var $_LoaderHelper \Epicor\Comm\Helper\LazyLoader */
$isLazyLoad = $_LoaderHelper->isLazyLoad();
$eccHideCheckout = $commHelper->getEccHidePrice();
$eccHideCheckout = $eccHideCheckout && $eccHideCheckout != 3 ? true : false;
$labelHelper = $this->helper('Codazon\ProductLabel\Helper\Data');
$_helper = $this->helper('Magento\Catalog\Helper\Output');

switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = true;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like:');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like:');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = true;
            $canItemsAddToCart = false;
        }
        break;

    case 'substitute-rule':
        /** @var \Epicor\Comm\Block\Catalog\Product\ProductList\Substitute $block */
        if ($exist = $block->hasItems()) {
            $type = $block->getDisplayType();
            $class = $block->getDisplayClass();

            $image = $block->getDisplayImagesClass();;
            $title = __('Substitute Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = true;
            $canItemsAddToCart = true;
        }
        break;

    case 'substitute':
        /** @var \Epicor\Comm\Block\Catalog\Product\ProductList\Substitute $block */
        if ($exist = ($block->isDisplayExist() && count($block->getItems()))) {
            $type = $block->getDisplayType();
            $class = $block->getDisplayClass();

            $image = $block->getDisplayImagesClass();;
            $title = __('Substitute Products');
            $items = $block->getItems();
            $limit = $block->getItemLimit('substitute');
            $shuffle = 0;

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = true;
            $canItemsAddToCart = true;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}

$loadedIds = array();
?>

<?php if ($exist):?>
<?php
$epicorEccBlock = $block->getLayout()->createBlock('Epicor\Comm\Block\Catalog\Product\ListProduct');
$epicorEccBlock->setCollection([]);
$epicorEccBlock->setListMode("grid");
?>
<?php if ($type == 'related' || $type == 'upsell' || ($type == 'substitute' && !$block->isCartView())): ?>
<?php if ($type == 'related'): ?>
<div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
    <?php else: ?>
    <div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php endif; ?>
        <?php else: ?>
        <div class="block <?= /* @escapeNotVerified */ $class ?>">
            <?php endif; ?>
            <div class="block-title title">
                <strong id="block-<?= /* @escapeNotVerified */ $class ?>-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title ?></strong>
            </div>
            <div class="related-upsell-crossell block-content content" aria-labelledby="block-<?= /* @escapeNotVerified */ $class ?>-heading">
                <div class="products wrapper grid products-grid products-<?= /* @escapeNotVerified */ $type ?>">
                    <ol class="products list items product-items">
                        <?php foreach ($items as $_item): ?>
                            <?php $epicorEccBlock->setProductPrices($_item); ?>
                            <?php $epicorEccBlock->setCurrentProduct($_item); ?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($type == 'related' || $type == 'upsell' || ($type == 'substitute' && !$block->isCartView())): ?>
                                <li class="item product product-item" style="display: none;">
                            <?php else: ?>
                                <li class="item product product-item">
                            <?php endif; ?>
                            <div class="product-item-info <?= /* @escapeNotVerified */ $available ?>">
                                <div class="cdz-hover-section">
                                    <div class="cdz-product-top">
                                        <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
                                        <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                            <?= $block->getImage($_item, $image)->toHtml() ?>
                                        </a>
                                    </div>
                                </div>

                                <?php
                                /**
                                 * Please Don't forgot to add
                                 * css class "ecc-price-lazy-load-<type>" and
                                 * "ecc-data-product-id" attribute with
                                 * your custom theme to work lazy load with FPC and Price Msq
                                 *
                                 */
                                ?>
                                <div class="product details product-item-details ecc-price-lazy-load-<?php echo $type; ?>" ecc-data-product-id="<?php echo $_item->getId(); ?>">
                                    <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                                        <?= $block->escapeHtml($_item->getName()) ?></a>
                                    </strong>
                                    <?php $labelHelper->showLabel($_item) ?>
                                    <?php if ( ! $isLazyLoad): /** ECC Lazy load enable START */ ?>
                                        <?php // ECC PRICE START >>> ?>
                                        <?php if ($epicorEccBlock->showPriceOnConfiguration($_item)): ?>
                                            <div class="price-box"><span class="price"><?php echo __('Price on configuration'); ?></span></div>
                                        <?php else: ?>
                                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item) ?>
                                        <?php endif; ?>
                                        <?php // ECC PRICE END <<< ?>
                                        <?php if ($showAddTo || $showCart): ?>
                                            <?php //if ($showCart): ?>
                                            <div class="cdz-product-bottom hover-effect">
                                                <div class="cdz-buttons-container">
                                                    <div class="cdz-buttons-inner"> <?php //endif; ?>
                                            <div class="product actions product-item-actions">
                                                <?php $showAddToCart = true; ?>
                                                <?php if ($showCart && $epicorEccBlock->showAddToCart($_item) && !$eccHideCheckout): $showAddToCart = true; ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable() && !$_item->canConfigure()): ?>
                                                            <?php if ($epicorEccBlock->showLocations()): ?>
                                                                <?php echo $this->getChildHtml('epicor_ecc_product_list_locations', false); ?>
                                                            <?php elseif ($_item->getEccConfigurator()): ?>
                                                                <?php echo $this->getChildHtml('epicor_ecc_product_configurator', false) ?>
                                                            <?php elseif ($_item->getTypeId() == 'grouped' || $_item->getTypeId() == 'configurable'): ?>
                                                                <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $_item->getProductUrl() ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('View Details') ?>">
                                                                    <span><?= /* @escapeNotVerified */ __('View Details') ?></span>
                                                                </button>
                                                            <?php else: ?>
                                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                                    </button>
                                                                <?php else: ?>
                                                                    <?php //$postParams = $block->getAddToCartPostParams($_item); ?>
                                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                    $paramData = [];
                                                                    if ($_item->getTypeId() == 'bundle') {
                                                                        $selectionCollection = $_item->getTypeInstance(true)->getSelectionsCollection(
                                                                            $_item->getTypeInstance(true)->getOptionsIds($_item),
                                                                            $_item
                                                                        );
                                                                        foreach ($selectionCollection as $option) {
                                                                            $paramData["bundle_option[" . $option['option_id'] . "]"] = $option['selection_id'];
                                                                        }
                                                                    }
                                                                    if ($epicorEccBlock->getSingleLocation()) {
                                                                        $paramData['location_code'] = $epicorEccBlock->getSingleLocation()->getLocationCode();;
                                                                    }
                                                                    $paramData['product'] = $_item->getEntityId();
                                                                    //$paramData[Action::PARAM_NAME_URL_ENCODED] = $postParams['data'][Action::PARAM_NAME_URL_ENCODED];
                                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item),
                                                                        $paramData)
                                                                    ?>
                                                                    <button class="action tocart primary"
                                                                            data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                                            type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                                    </button>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        <?php elseif($_item->isSaleable() && $_item->canConfigure()): ?>
                                                            <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $_item->getProductUrl() ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('View Details') ?>">
                                                                <span><?= /* @escapeNotVerified */ __('View Details') ?></span>
                                                            </button>
                                                        <?php else: ?>
                                                            <div class="stock unavailable"><span><?php echo __('Product currently unavailable'); ?></span></div>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                                <?php if($showCart && (!$showAddToCart || $eccHideCheckout)): ?>
                                                    <?php if (($_item->getStockItem() && $_item->getStockItem()->getIsInStock())): ?>
                                                        <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $_item->getProductUrl() ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('View Details') ?>">
                                                            <span><?= /* @escapeNotVerified */ __('View Details') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php echo __('Product currently unavailable'); ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                                <?php if ($showAddTo): ?>
                                                    <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                            <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                            <?php //if ($showCart): ?> </div></div></div> <?php //endif; ?>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php /** ECC Lazy load collect array product */ ?>
                                        <?php $loadedIds[] = $_item->getId(); ?>
                                    <?php endif; /** ECC Lazy load enable END <<< */ ?>
                                </div>
                            </div>
                            </li>
                        <?php endforeach ?>
                        <?php /* Lazy load for upsell, crosssell, related, substitute and new product */ ?>
                        <?php if ($isLazyLoad && count($loadedIds) > 0): ?>
                            <?php
                            $config["sendMessageUrl"] = $_LoaderHelper->getLoaderUrl();
                            $config["productIds"] = $loadedIds;
                            $config["loaderImageUrl"] = $_LoaderHelper->getLoaderImageUrl() ?: $this->getViewFileUrl("images/loader-2.gif");
                            $config["viewType"] = $type;
                            ?>
                            <script type="text/javascript">
                              //<![CDATA[
                              require([
                                "jquery",
                                'mage/translate',
                                'Epicor_Comm/epicor/comm/js/lazy-load'
                              ], function ($, $tr, lazyLoad) {
                                $(document).ready(function (element) {
                                  var config =<?php echo json_encode($config)?>;
                                  payment = new lazyLoad(config);
                                });
                              });
                              //]]>
                            </script>
                        <?php endif; ?>
                    </ol>
                </div>
            </div>
        </div>
        <?php endif;?>
<?php
    $itemSlider = 4;
    if($type == 'crosssell' || $type == 'crosssell-rule'){
        $itemSlider = $itemSlider - 1;
    }
?>
<script type="text/javascript">
require(['jquery','cdz_slider'],function($){
    if($('.related-upsell-crossell .products-<?php /* @escapeNotVerified */ echo $type; ?> .product-items').length)
    {
        $('.related-upsell-crossell .products-<?php /* @escapeNotVerified */ echo $type; ?> .product-items').addClass('owl-carousel');
        $('.related-upsell-crossell .products-<?php /* @escapeNotVerified */ echo $type; ?> .product-items').owlCarousel({
            items:<?php echo $itemSlider ?>,
            lazyLoad: true,
            loop: false,
            margin: 20,
            responsiveClass: true,
            nav: true,
            dots: true,
            rtl: ThemeOptions.rtl_layout == 1 ? true : false,
            responsive:{
                0:{items: <?php echo ($itemSlider > 2)  ?>},
                480:{items: <?php echo ($itemSlider > 2)   ?>},
                640:{items: <?php echo ($itemSlider > 2)  ?>},
                768:{items: <?php echo  ($itemSlider - 1) ?>},
                1200:{items: <?php echo $itemSlider ?>}
            }
        });
    }
})
</script>
